/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{vue,js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "secondary-fixed-dim": "#ffb4a3",
                "secondary-fixed": "#ffdad2",
                "primary": "#00696d",
                "surface-container-high": "#e7e8e9",
                "tertiary-container": "#b0a8c0",
                "surface-tint": "#00696d",
                "secondary": "#ae3115",
                "tertiary": "#615b71",
                "surface-dim": "#d9dadb",
                "on-tertiary-fixed": "#1d192b",
                "error-container": "#ffdad6",
                "secondary-container": "#fd6a49",
                "on-primary": "#ffffff",
                "inverse-on-surface": "#f0f1f2",
                "primary-container": "#00bec4",
                "on-tertiary-container": "#423d51",
                "tertiary-fixed-dim": "#cbc3dc",
                "tertiary-fixed": "#e7def8",
                "surface-container-lowest": "#ffffff",
                "on-primary-fixed-variant": "#004f52",
                "surface": "#f8f9fa",
                "on-secondary-fixed": "#3d0600",
                "surface-variant": "#e1e3e4",
                "surface-bright": "#f8f9fa",
                "on-background": "#191c1d",
                "background": "#f8f9fa",
                "on-secondary-container": "#640f00",
                "on-tertiary-fixed-variant": "#494458",
                "on-secondary": "#ffffff",
                "on-secondary-fixed-variant": "#8c1900",
                "inverse-surface": "#2e3132",
                "on-surface-variant": "#3c494a",
                "primary-fixed": "#68f7fd",
                "on-primary-fixed": "#002021",
                "surface-container-low": "#f3f4f5",
                "outline-variant": "#bbc9ca",
                "surface-container-highest": "#e1e3e4",
                "error": "#ba1a1a",
                "on-primary-container": "#00474a",
                "surface-container": "#edeeef",
                "primary-fixed-dim": "#43dae0",
                "on-surface": "#191c1d",
                "outline": "#6c7a7a",
                "on-tertiary": "#ffffff",
                "on-error-container": "#93000a",
                "inverse-primary": "#43dae0",
                "on-error": "#ffffff"
            },
            borderRadius: {
                DEFAULT: "1rem",
                lg: "2rem",
                xl: "3rem",
                full: "9999px"
            },
            spacing: {
                "stack-lg": "48px",
                "gutter": "16px",
                "base": "8px",
                "stack-md": "24px",
                "stack-sm": "12px",
                "container-padding": "24px"
            },
            fontFamily: {
                "body-md": ["Be Vietnam Pro", "sans-serif"],
                "headline-md": ["Sora", "sans-serif"],
                "headline-lg": ["Sora", "sans-serif"],
                "label-md": ["Be Vietnam Pro", "sans-serif"],
                "headline-xl": ["Sora", "sans-serif"],
                "headline-lg-mobile": ["Sora", "sans-serif"],
                "body-lg": ["Be Vietnam Pro", "sans-serif"]
            },
            fontSize: {
                "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
                "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
                "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
                "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
            }
        },
    },
    plugins: [],
}